### ISSUE TITLE
Please create a release binary

### ISSUE THREAD

**Issue by MKGitHub** [johnno1962/GitDiff9#2]
Please create a release binary, ready for download and usage without having to build.

thx

**Comment by johnno1962** [comment]
The easiest way to install the plugin given it needs to be installed in ~/Library is to build it.

**Comment by johnno1962** [comment]
I’ve renamed this repo to be the default so this installs now from Alcatraz if that helps.

**Comment by MKGitHub** [comment]
ok thx
